Style:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Layout/LineLength:
  Max: 100
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Metrics/ClassLength:
  Max: 150
Metrics/ModuleLength:
  Max: 150
Lint/UnreachableCode:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Naming/VariableNumber:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/PerceivedComplexity:
  Max: 20
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Max: 35
  Exclude:
    - '**/config/routes.rb'
    - '**/config/routes/*'
    - '**/config/environments/*'
    - '**/config/initializers/*'
AllCops:
  TargetRubyVersion: 3.3.1
  Exclude:
    - '**/bin/*'
    - '**/db/schema.rb'
    - '**/db/queue_schema.rb'
    - '**/db/migrate/*'
    - '**/config/initializers/*'
    - '**/vendor/bundle/**/*'
    - '**/spec/**/*'